// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8nEiJL_ir83uCUOOiJmtlFQ8vOt-g9xY',
    appId: '1:453542456893:web:383207f16e658a8c9f8454',
    messagingSenderId: '453542456893',
    projectId: 'servehome-ae236',
    authDomain: 'servehome-ae236.firebaseapp.com',
    storageBucket: 'servehome-ae236.firebasestorage.app',
    measurementId: 'G-17RZX2M890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhYZOO3ScNQz0wZ5quAXVf-2QhaIXUkU',
    appId: '1:453542456893:android:db6731efd30a74769f8454',
    messagingSenderId: '453542456893',
    projectId: 'servehome-ae236',
    storageBucket: 'servehome-ae236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_5be-2IJVH7a-AdBNBCBBN9ydAgrfn0',
    appId: '1:453542456893:ios:588c271674dbe8259f8454',
    messagingSenderId: '453542456893',
    projectId: 'servehome-ae236',
    storageBucket: 'servehome-ae236.firebasestorage.app',
    iosClientId: '453542456893-9joio5clnbah0il61debtroho95nfsbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.serveHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_5be-2IJVH7a-AdBNBCBBN9ydAgrfn0',
    appId: '1:453542456893:ios:588c271674dbe8259f8454',
    messagingSenderId: '453542456893',
    projectId: 'servehome-ae236',
    storageBucket: 'servehome-ae236.firebasestorage.app',
    iosClientId: '453542456893-9joio5clnbah0il61debtroho95nfsbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.serveHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8nEiJL_ir83uCUOOiJmtlFQ8vOt-g9xY',
    appId: '1:453542456893:web:81b1f9424de788be9f8454',
    messagingSenderId: '453542456893',
    projectId: 'servehome-ae236',
    authDomain: 'servehome-ae236.firebaseapp.com',
    storageBucket: 'servehome-ae236.firebasestorage.app',
    measurementId: 'G-T2Y0KLJGC7',
  );
}
